[project]
name = "Role-based-Governance"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/Role-based-Governance/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.Role-based-Governance]
path = "contracts/Role-based-Governance.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
